version: '3.9'

services:
  axum:
    container_name: axum
    build:
      context: ./axum
      dockerfile: Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
          condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}"

  svelte:
    container_name: svelte
    build:
      context: ./svelte
      dockerfile: Dockerfile
    volumes:
      - ./svelte:/app
    ports:
      - '5173:5173'

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PGUSER --dbname $PGDATABASE"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
