version: '3.9'

services:
  axum:
    container_name: axum
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: amrrz
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


volumes:
  pg_data:
